# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-executables-have-shebangs
  - id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.7.1
  hooks:
  - id: prettier
    types_or: [css, javascript]
    additional_dependencies:
    - prettier@2.7.1
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.25.0
  hooks:
  - id: eslint
    files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
    types: [file]
    additional_dependencies:
    - eslint@8.2.0
    - prettier@2.7.1
    - "@babel/cli@7.16.0"
    - "@babel/core@7.16.5"
    - "@babel/eslint-parser@7.19.1"
    - "@babel/runtime@7.16.5"
    - eslint-config-airbnb@19.0.4
    - eslint-config-prettier@7.1.0
    - eslint-import-resolver-alias@1.1.2
    - eslint-plugin-import@2.26.0
    - eslint-plugin-jest@24.3.6
    - eslint-plugin-jsx-a11y@6.6.1
    - eslint-plugin-react@7.31.10
    - eslint-plugin-react-hooks@4.6.0
    - eslint-plugin-simple-import-sort@7.0.0
    - "@typescript-eslint/eslint-plugin@5.40.1"
    - "@typescript-eslint/parser@5.40.1"
- repo: https://github.com/pre-commit/mirrors-scss-lint
  rev: v0.59.0
  hooks:
  - id: scss-lint
- repo: https://github.com/pre-commit/mirrors-csslint
  rev: v1.0.5
  hooks:
  - id: csslint
